name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/master' }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn

      - run: yarn run release

      - run: yarn run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
